# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-28 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_cus_day', models.IntegerField(verbose_name='每日增加客户数')),
                ('add_lia_day', models.IntegerField(verbose_name='每日增加联系人数')),
                ('add_bus_day', models.IntegerField(verbose_name='每日增加商机数')),
                ('add_rec_day', models.IntegerField(verbose_name='每日增加拜访记录数')),
                ('add_cus_month', models.IntegerField(verbose_name='每月增加客户数')),
                ('add_lia_month', models.IntegerField(verbose_name='每月增加联系人数')),
                ('add_bus_month', models.IntegerField(verbose_name='每月增加商机数')),
                ('add_rec_month', models.IntegerField(verbose_name='每月增加拜访记录数')),
                ('all_cus', models.IntegerField(verbose_name='个人客户总数')),
                ('all_lia', models.IntegerField(verbose_name='个人联系人总数')),
                ('all_bus', models.IntegerField(verbose_name='个人商机总数')),
                ('all_rec', models.IntegerField(verbose_name='个人拜访记录总数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '数据汇总',
                'verbose_name_plural': '数据汇总',
                'db_table': 'counts',
            },
        ),
    ]
