# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-09 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='add_bus_day',
            new_name='add_bus',
        ),
        migrations.RenameField(
            model_name='count',
            old_name='add_cus_day',
            new_name='add_cus',
        ),
        migrations.RenameField(
            model_name='count',
            old_name='add_lia_day',
            new_name='add_lia',
        ),
        migrations.RenameField(
            model_name='count',
            old_name='add_rec_day',
            new_name='add_rec',
        ),
        migrations.RemoveField(
            model_name='count',
            name='add_bus_month',
        ),
        migrations.RemoveField(
            model_name='count',
            name='add_cus_month',
        ),
        migrations.RemoveField(
            model_name='count',
            name='add_lia_month',
        ),
        migrations.RemoveField(
            model_name='count',
            name='add_rec_month',
        ),
        migrations.RemoveField(
            model_name='count',
            name='all_bus',
        ),
        migrations.RemoveField(
            model_name='count',
            name='all_cus',
        ),
        migrations.RemoveField(
            model_name='count',
            name='all_lia',
        ),
        migrations.RemoveField(
            model_name='count',
            name='all_rec',
        ),
    ]
