# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-13 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201009_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='add_bus',
            field=models.IntegerField(default=0, verbose_name='每日增加商机数'),
        ),
        migrations.AlterField(
            model_name='count',
            name='add_cus',
            field=models.IntegerField(default=0, verbose_name='每日增加客户数'),
        ),
        migrations.AlterField(
            model_name='count',
            name='add_lia',
            field=models.IntegerField(default=0, verbose_name='每日增加联系人数'),
        ),
        migrations.AlterField(
            model_name='count',
            name='add_rec',
            field=models.IntegerField(default=0, verbose_name='每日增加拜访记录数'),
        ),
    ]
