# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-24 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201013_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('power', models.SmallIntegerField(choices=[(1, '业务'), (2, '主管'), (3, '商务'), (4, '经理'), (5, '人事')], default=1, verbose_name='权限')),
            ],
        ),
        migrations.AlterField(
            model_name='count',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count', to='users.User'),
        ),
    ]
