# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-25 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201124_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelTable(
            name='count',
            table='user_counts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
