# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-11 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='客户名称')),
                ('rank', models.SmallIntegerField(choices=[(1, '重点客户'), (2, '一般客户'), (3, '普通客户')], default=1, verbose_name='客户级别')),
                ('phone', models.CharField(max_length=11, verbose_name='客户联系方式')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer',
                'ordering': ['created_at', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoiceAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('city', models.CharField(max_length=32, verbose_name='市区')),
                ('area', models.CharField(max_length=32, verbose_name='区域')),
                ('town', models.CharField(blank=True, max_length=32, null=True, verbose_name='街道')),
                ('address', models.CharField(max_length=64, verbose_name='详细地址')),
                ('username', models.CharField(max_length=32, verbose_name='收货人')),
                ('phone', models.CharField(max_length=32, verbose_name='收货人电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice_address', to='customer.Customer')),
            ],
            options={
                'verbose_name': '客户发票地址',
                'verbose_name_plural': '客户发票地址',
                'db_table': 'customer_invoice_address',
            },
        ),
        migrations.CreateModel(
            name='CustomerShopAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('city', models.CharField(max_length=32, verbose_name='市区')),
                ('area', models.CharField(max_length=32, verbose_name='区域')),
                ('town', models.CharField(blank=True, max_length=32, null=True, verbose_name='街道')),
                ('address', models.CharField(max_length=64, verbose_name='详细地址')),
                ('username', models.CharField(max_length=32, verbose_name='收货人')),
                ('phone', models.CharField(max_length=32, verbose_name='收货人电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_shop_address', to='customer.Customer')),
            ],
            options={
                'verbose_name': '客户收货地址',
                'verbose_name_plural': '客户收货地址',
                'db_table': 'customer_shop_address',
            },
        ),
    ]
