# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-11 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='客户名称'),
        ),
    ]
