# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-21 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200921_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoiceaddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice_address', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='customershopaddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_shop_address', to='customer.Customer'),
        ),
    ]
