# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-21 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200921_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, verbose_name='客户行业')),
            ],
            options={
                'verbose_name': '客户行业',
                'verbose_name_plural': '客户行业',
                'db_table': 'cus_industry',
            },
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, verbose_name='性质名称')),
            ],
            options={
                'verbose_name': '客户性质',
                'verbose_name_plural': '客户性质',
                'db_table': 'cus_nature',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='scale',
            field=models.SmallIntegerField(choices=[(11, '0~10人'), (22, '10~50人'), (33, '50~100人'), (44, '100~1000人'), (55, '1000人及以上')], default=11, verbose_name='客户规模'),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='customer.Industry', verbose_name='客户行业'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='nature',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='customer.Nature', verbose_name='客户性质'),
            preserve_default=False,
        ),
    ]
