# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-22 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200921_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Industry', verbose_name='客户行业'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Nature', verbose_name='客户性质'),
        ),
    ]
