# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-22 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200922_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客户网址'),
        ),
    ]
