# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-24 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20200922_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoiceaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customershopaddress',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='发票详细地址'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_area',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='发票区域'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='发票收货人电话'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_province',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='发票省份'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_town',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='发票街道'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='发票地收货人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop_address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='收货详细地址'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop_area',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='收货区域'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop_city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='收货市区'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop_phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='收货收货人电话'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop_province',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='收货省份'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop_town',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='收货街道'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop_username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='收货地收货人'),
        ),
        migrations.DeleteModel(
            name='CustomerInvoiceAddress',
        ),
        migrations.DeleteModel(
            name='CustomerShopAddress',
        ),
    ]
