# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-25 02:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0012_customer_at_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='at_user',
        ),
        migrations.AddField(
            model_name='customer',
            name='belong_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='belong_user', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
            preserve_default=False,
        ),
    ]
