# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-28 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20200925_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='belong_user',
        ),
    ]
