# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-14 01:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200912_1412'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商机名称')),
                ('winning_rate', models.SmallIntegerField(choices=[(21, '20%'), (22, '50%'), (23, '80%')], default=21, verbose_name='赢单率')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='商机备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='商机客户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_business', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户商机',
                'verbose_name_plural': '客户商机',
                'db_table': 'cus_business',
            },
        ),
        migrations.RemoveField(
            model_name='businessopportunity',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='businessopportunity',
            name='user',
        ),
        migrations.DeleteModel(
            name='BusinessOpportunity',
        ),
    ]
