# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-18 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200914_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbusiness',
            name='winning_rate',
            field=models.SmallIntegerField(choices=[(20, '0%'), (21, '20%'), (22, '50%'), (23, '80%'), (24, '100%')], default=21, verbose_name='赢单率'),
        ),
    ]
