# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-28 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_customerbusiness_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='货品名称')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('price', models.FloatField(max_length=64, verbose_name='价格')),
            ],
            options={
                'verbose_name': '商机产品',
                'verbose_name_plural': '商机产品',
                'db_table': 'bus_product',
            },
        ),
        migrations.AddField(
            model_name='customerbusiness',
            name='product',
            field=models.ManyToManyField(to='business.Product', verbose_name='力推产品'),
        ),
    ]
