# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-02 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20201028_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbusiness',
            name='product',
        ),
        migrations.AddField(
            model_name='customerbusiness',
            name='prod_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='货品名称'),
        ),
        migrations.AddField(
            model_name='customerbusiness',
            name='prod_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='customerbusiness',
            name='prod_price',
            field=models.FloatField(blank=True, max_length=64, null=True, verbose_name='价格'),
        ),
    ]
