# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-25 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20201102_1404'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerbusiness',
            table='business',
        ),
    ]
