# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-12 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_auto_20200911_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商机名称')),
                ('winning_rate', models.SmallIntegerField(choices=[(21, '20%'), (22, '50%'), (23, '80%')], default=21, verbose_name='赢单率')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='商机备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='商机客户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_opportunity', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户商机',
                'verbose_name_plural': '客户商机',
                'db_table': 'bus_oppor',
            },
        ),
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.TextField(max_length=1000, verbose_name='主要事宜')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='拜访备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_record', to='customer.Customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '客户拜访记录',
                'verbose_name_plural': '客户拜访记录',
                'db_table': 'cus_record',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, verbose_name='状态名称')),
            ],
            options={
                'verbose_name': '客户状态',
                'verbose_name_plural': '客户状态',
                'db_table': 'cus_status',
            },
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Status', verbose_name='客户状态'),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_record', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
