# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-14 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_customerrecord_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessopportunity',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='businessopportunity',
            name='user',
        ),
        migrations.DeleteModel(
            name='BusinessOpportunity',
        ),
    ]
