# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-25 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20200914_0905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerrecord',
            table='record',
        ),
        migrations.AlterModelTable(
            name='status',
            table='rec_status',
        ),
    ]
