# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-11 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='联系人姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系人电话')),
                ('job', models.SmallIntegerField(choices=[(12, '经理'), (13, '采购'), (14, '技术'), (15, '售后'), (11, '业务')], default=11, verbose_name='职称')),
                ('injob', models.BooleanField(choices=[(1, '在职'), (0, '离职')], default=1, verbose_name='是否在职')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaison', to='customer.Customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaison', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'db_table': 'liaison',
            },
        ),
    ]
