# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-12 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liaison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaison', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
