# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-18 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaison', '0002_auto_20200912_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaison',
            name='injob',
            field=models.SmallIntegerField(choices=[(31, '在职'), (30, '离职')], default=31, verbose_name='是否在职'),
        ),
    ]
