# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaison', '0003_auto_20200918_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaison',
            name='injob',
            field=models.SmallIntegerField(choices=[(1, '在职'), (0, '离职')], default=1, verbose_name='是否在职'),
        ),
    ]
