# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-22 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaison', '0004_auto_20200921_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='liaison',
            name='birthday',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='liaison',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AddField(
            model_name='liaison',
            name='hobby',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='兴趣爱好'),
        ),
        migrations.AddField(
            model_name='liaison',
            name='qq',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='liaison',
            name='wx',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信'),
        ),
    ]
