# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-28 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaison', '0005_auto_20200922_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaison',
            name='job',
            field=models.SmallIntegerField(choices=[(12, '经理'), (13, '采购'), (14, '技术'), (15, '售后'), (11, '业务'), (16, '其他')], default=11, verbose_name='职称'),
        ),
    ]
